spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.95.178.56:3306/spm?useUnicode=true&characterSetResults=utf8mb4
    username: root
    password: 1234

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换

    #动态sql配置
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.spm.model

